import type { Metadata } from 'next'
import './globals.css'
import { ProductFont } from '@/components/fonts'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ProductFont.className}>{children}</body>
    </html>
  )
}
